name: Teste Github Actions

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: maven

      - name: Versão do Java
        run: java -version

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb
          sudo apt-get install -f # Installs dependencies

      - name: Verificar versão do Chrome
        run: google-chrome --version

      - name: Verificar versão do Chromedriver
        run: chromedriver --version

      - name: Start Xvfb
        run: |
          export DISPLAY=:99.0
          sudo Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Run Tests
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting || true

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml